language: python	
python:	3.6.4
cache: pip	
install:	
  pip install -r requirements.txt
  pip install coveralls
  pip install codeclimate-test-reporter
script:	
  nosetests api/tests --with-coverage
after_success:
  coveralls
codeclimate-test-reporter