language: python	
python:	
  - "3.6.4"
cache: pip	
install:
  - pip install codecov	
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter
script:	
  - nosetests --with-coverage --cover-package=app,tests
after_success:
  - codecov
  - coveralls COVERALLS_REPO_TOKEN=WKCE2ey286UIeaDv6faJbK45JVBdTwfFH
 