language: python	
python:	
  - "3.6.4"
cache: pip	
install:	
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter
script:	nosetests --with-coverage
after_success:
  - coveralls COVERALLS_REPO_TOKEN=WKCE2ey286UIeaDv6faJbK45JVBdTwfFH
  - codeclimate-test-reporter